fix manifest and deployment pipeline file

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -19,16 +19,21 @@ stages:
       #export PATH=/opt/IBM/node-v4.2/bin:$PATH
       
       # Build web client
-      cd ./webclient
-      npm install
-      npm run tsc
-      if [ $NPM_ENV == 'production' ]; then
-        npm run bundle:prod
+      if [ -d ./webclient ]; then
+        pushd .
+        cd ./webclient
+        echo "-- Installing dependencies..."
+        npm install
+        echo "-- Compiling typescript..."
+        npm run tsc
+        if [ "$NPM_ENV" = "production" ]; then
+          echo "-- Building bundle for production..."
+          npm run bundle:prod
+        fi
         # Cleaning up node_modules
         rm -Rf ./node_modules
+        popd
       fi
-      cd ..
-      
       # if necessary
       #npm install
 - name: Deploy Stage
@@ -47,24 +52,30 @@ stages:
        url: ${CF_TARGET_URL}
        application: ${CF_APP}
     script: |
-     #!/bin/bash
-
-     if [ ! -f _generate_deploy_files.sh ]; then
-       echo "The _generate_deploy_files.sh is missing. Exiting.."
-       exit 1
-     fi
-     echo "Generating deployment files for suffix '$SUFFIX'"
-     chmod +x _generate_deploy_files.sh
-     ./_generate_deploy_files.sh $SUFFIX || exit 1
-     echo "Generated _deploy_create_services.sh"
-     cat _deploy_create_services.sh
-     echo "--"
-     echo "Generated manifest.yml"
-     cat manifest.yml
-     echo "--"
-
-     # create services
-     [ -f "_deploy_create_services.sh" ] && source _deploy_create_services.sh || echo "no create services script"
-     cf push "${CF_APP}"
-     # View logs
-     #cf logs "${CF_APP}" --recent
+      #!/bin/bash
+      
+      if [ ! -f _generate_deploy_files.sh ]; then
+        echo "The _generate_deploy_files.sh is missing. Exiting.."
+        exit 1
+      fi
+      echo "Generating deployment files for suffix '$SUFFIX'"
+      chmod +x _generate_deploy_files.sh
+      ./_generate_deploy_files.sh $SUFFIX || exit 1
+      echo "Generated _deploy_create_services.sh"
+      cat _deploy_create_services.sh
+      echo "--"
+      echo "Generated manifest.yml"
+      cat manifest.yml
+      echo "--"
+      if [[ $CF_TARGET_URL == *".stage1."* ]]; then
+        echo "*** Patching manifest.yml to remove IoT4A service in stage1 ***"
+        sed -i.bak '/- FleetIoTForAuto/d' ./manifest.yml
+        cat manifest.yml
+        echo "--"
+      fi
+      
+      # create services
+      [ -f "_deploy_create_services.sh" ] && source _deploy_create_services.sh || echo "no create services script"
+      cf push "${CF_APP}"
+      # View logs
+      #cf logs "${CF_APP}" --recent
